# plants.ipynb
Author: UFO Software, LLC<br>
Created: Sunday, February 14, 2021 15:17<br>

License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html> <br>
This is free software: you are free to change and redistribute it.<br>
There is NO WARRANTY, to the extent permitted by law.<br>
<br>
Reads in the Plants_0.csv file from the [December 2020 WA State Traceability Data](https://lcb.app.box.com/s/fnku9nr22dhx04f6o646xv6ad6fswfy9?page=1)<br>
The file has a partial column that casue a Pandas error; this notebook compensates for that by only reading the valid columns bys using the usecols parameter of the read_csv function.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import os

import seaborn as sns
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix

# change to point to the data's location
file_path = Path('../dec-2020')
pd.set_option('display.max_columns', None)

In [2]:
def get_plants_df():
    # The Plants_0.csv file has a parital column that pandas errors out on.  To fix this just read in the valid columns using the usecols paramter of the read_csv function.
    col_dtypes = {'global_id' : 'string',
                  'mme_id' : 'string',
                  'user_id' : 'string',
                  'external_id' : 'string',
                  'inventory_id' : 'string',
                  'batch_id' : 'string',
                  'area_id' : 'string',
                  'mother_plant_id' : 'string',
                  'is_initial_inventory' : 'bool',
                  'origin' : 'string',
                  'stage' : 'string',
                  'strain_id' : 'string',
                  'is_mother' : 'bool',
                  'legacy_id' : 'string'
                 }

    # parse the columns containing dates
    # there are some issues with the date columns in this file, as a temporary fix I'm treating them as strings
    date_cols = {'created_at' : 'string',
                # 'deleted_at' : 'string',
                 'updated_at' : 'string',
                 'plant_created_at' : 'string',
                 'plant_harvested_at' : 'string',
                 #'last_moved_at' : 'string',
                 #'plant_harvested_end_at' : 'string'
                }

    # combine the column names to load only the columns you are using
    cols = list(col_dtypes.keys()) + list(date_cols.keys())

    plants_df = pd.read_csv(file_path / 'Plants_0.csv', sep = '\t', encoding = 'utf-16', usecols = cols, dtype = col_dtypes)
    
    #u = plants_df.select_dtypes(include=['datetime'])
   # plants_df[u.columns] = u.fillna(pd.to_datetime('1900-01-01'))
    return plants_df

In [3]:
plants_df = get_plants_df()
plants_df.head()

,global_id,created_at,mme_id,user_id,external_id,inventory_id,updated_at,batch_id,area_id,mother_plant_id,plant_created_at,plant_harvested_at,is_initial_inventory,origin,stage,strain_id,is_mother,legacy_id
0,WAJ412598.PL1,2018-01-31 17:40:18,WAWA1.MMDJ,WAWA1.USAM,<NA>,<NA>,2020-10-05 05:13:07,WAJ412598.BAKRWNH,WAJ412598.AR5XZL,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,True,plant,destroyed,WAJ412598.ST7150,False,4125980000001207
1,WAJ412598.PL2,2018-01-31 17:40:20,WAWA1.MMDJ,WAWA1.USAM,<NA>,<NA>,2020-10-05 05:13:06,WAJ412598.BAKRWNH,WAJ412598.AR5XZL,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,True,plant,destroyed,WAJ412598.ST7150,False,4125980000001422
2,WAJ412598.PL3,2018-01-31 17:40:24,WAWA1.MMDJ,WAWA1.USAM,<NA>,<NA>,2020-10-05 05:13:05,WAJ412598.BAKRWNH,WAJ412598.AR5XZL,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,True,plant,destroyed,WAJ412598.ST7150,False,4125980000002064
3,WAJ412598.PL4,2018-01-31 17:40:28,WAWA1.MMDJ,WAWA1.USAM,<NA>,<NA>,2020-10-05 05:13:04,WAJ412598.BAKRWNH,WAJ412598.AR5XZL,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,True,plant,destroyed,WAJ412598.ST7150,False,4125980000003419
4,WAJ412598.PL5,2018-01-31 17:40:25,WAWA1.MMDJ,WAWA1.USAM,<NA>,<NA>,2020-10-20 08:12:35,WAJ412598.BAL2EFP,WAJ412598.AR5XZL,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,True,plant,destroyed,WAJ412598.STX,False,4125980000003424

In [4]:
plants_df.tail()

,global_id,created_at,mme_id,user_id,external_id,inventory_id,updated_at,batch_id,area_id,mother_plant_id,plant_created_at,plant_harvested_at,is_initial_inventory,origin,stage,strain_id,is_mother,legacy_id
22185200,WAJ414395.PLD9BXP,2021-01-06 12:32:36,WAWA1.MMBP,WAWA1.USLT5,<NA>,<NA>,2021-01-06 12:32:36,WAJ414395.BAMFJ6T,WAJ414395.ARCZT,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,False,clone,growing,WAJ414395.STQDZY,False,<NA>
22185201,WAJ414395.PLD9BXQ,2021-01-06 12:32:36,WAWA1.MMBP,WAWA1.USLT5,<NA>,<NA>,2021-01-06 12:32:36,WAJ414395.BAMFJ6T,WAJ414395.ARCZT,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,False,clone,growing,WAJ414395.STQDZY,False,<NA>
22185202,WAJ414395.PLD9BXR,2021-01-06 12:32:36,WAWA1.MMBP,WAWA1.USLT5,<NA>,<NA>,2021-01-06 12:32:36,WAJ414395.BAMFJ6T,WAJ414395.ARCZT,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,False,clone,growing,WAJ414395.STQDZY,False,<NA>
22185203,WAJ414395.PLD9BXS,2021-01-06 12:32:36,WAWA1.MMBP,WAWA1.USLT5,<NA>,<NA>,2021-01-06 12:32:36,WAJ414395.BAMFJ6T,WAJ414395.ARCZT,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,False,clone,growing,WAJ414395.STQDZY,False,<NA>
22185204,WAJ414395.PLD9BXT,2021-01-06 12:32:36,WAWA1.MMBP,WAWA1.USLT5,<NA>,<NA>,2021-01-06 12:32:36,WAJ414395.BAMFJ6T,WAJ414395.ARCZT,<NA>,1900-01-01 00:00:00,1900-01-01 00:00:00,False,clone,growing,WAJ414395.STQDZY,False,<NA>

In [5]:
plants_df.describe()

,global_id,created_at,mme_id,user_id,external_id,inventory_id,updated_at,batch_id,area_id,mother_plant_id,plant_created_at,plant_harvested_at,is_initial_inventory,origin,stage,strain_id,is_mother,legacy_id
count,22185142,22185205,22185205,22185205,6088484,1336315,22185205,22185205,20941419,2847846,22185205,22185205,22185205,22096153,22148637,20941472,22185205,1047962
unique,22185142,3927047,1145,1994,5281329,308103,5292799,4421356,25811,99713,3726,57667,2,9,12,84928,2,980336
top,WAJ416744.PLADAH9,2020-11-04 00:15:09,WAWA1.MM13T,WAWA1.US61I,Digital Disposal license 412149 12\/14\/20,WAJ416046.INLSE7I,2020-12-14 11:13:51,WAG415764.BALC8EO,WAG415764.AR2YU,WAG416445.PL8XBM1,1900-01-01 00:00:00,1900-01-01 00:00:00,False,clone,harvested,WAG415764.STIU6C,False,TW: 15-Day
freq,1,238,1354641,1350874,135079,9285,135079,159301,1209486,91466,9934088,13326680,21744825,12215836,8799430,609891,20723154,895

In [6]:
# comment out if you are not planning on using Dask
plants_df.to_parquet(file_path / 'plants.parquet')